spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
         # search-locations: "classpath:/config/"
         # search-locations: "file:///F://microservices//config"
        git:
          uri: "https://github.com/shubhakshi22/microservices-configserver-latest.git"
          default-label: "main"
          timeout: 5 #config should wait only for 5 seconds otherwise through an exception.
          clone-on-start: true
          force-pull: true

encrypt:
  key: "12345678901234567890123456789012"

server:
  port: 8071
