spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
         # search-locations: "classpath:/config/"
         # search-locations: "file:///F://microservices//config"
        git:
          uri: "https://github.com/shubhakshi22/microservices-configserver-latest.git"
          default-label: "main"
          timeout: 5 #config should wait only for 5 seconds otherwise through an exception.
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "12345678901234567890123456789012"

server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
