spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Tom - Product Owner"
    email: "tom@eazybank.com"
  onCallSupport:
    - (493) 392-4829
    - (466) 203-3857